# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  project: 'SoftU2FDaemon/*.csproj'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '3.0.100-preview6-012264' # replace this value with the version that you need for your project

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: $(project)
    feedsToUse: config

- task: DotNetCoreCLI@2
  displayName: Publish win10-x64
  inputs:
    command: publish
    projects: $(project)
    arguments: '--configuration Release -r win10-x64 --output $(Build.ArtifactStagingDirectory)/win10-x64' # Update this to match your need

- task: DotNetCoreCLI@2
  displayName: Publish win10-x86
  inputs:
    command: publish
    projects: $(project)
    arguments: '--configuration Release -r win10-x64 --output $(Build.ArtifactStagingDirectory)/win10-x86' # Update this to match your need

